### Pima Indian Diabetes Dataset
#### Binary classification problem
##### # of feature : 8
###### feature 0: 과거 임신횟수
###### feature 1: 포도당 부하 검사 2시간 후 공복 혈당 농도
###### feature 2: 확장기 혈압
###### feature 3: 삼두근 피부 주름 두계
###### feature 4: 혈청 인슐린
###### feature 5: 체질량 지수
###### feature 6: 당뇨병 가족력
###### feature 7: 나이
###### output: 0(당뇨아님), 1(당뇨)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

#### feature names = ["pregnant", "plasma", "pressure", "thickness", "insulin", "BMI", "pedigree", "age", "class"])

In [2]:
input_file = './data/pima-indians-diabetes.data.csv'
data = np.loadtxt(input_file, delimiter=',')
x, y = data[:, :-1], data[:, -1]
print(data.shape)
print(x[0:5])
print(y[0:5])
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(768, 9)
[[6.000e+00 1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01
  5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]]
[1. 0. 1. 0. 1.]
(576, 8)
(576,)
(192, 8)
(192,)


In [3]:
# TODO: 여기에 필요한 package를 import 한다. 
from sklearn import svm
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier
# TODO: 코드 구현 

scaler = MinMaxScaler()

print("스케일 조정 전 특성별 최소값: \n", x_train.min(axis=0))
print("스케일 조정 전 특성별 최대값: \n", x_train.max(axis=0))
x_train = scaler.fit_transform(x_train)
print("변환 된 후 크기", x_train.shape)
print("스케일 조정 후 특성별 최소값: \n", x_train.min(axis=0))
print("스케일 조정 후 특성별 최대값: \n", x_train.max(axis=0))
x_test = scaler.transform(x_test)

result_train = 80
result_test = 80
result_X = 0
result_Y = 0
flag = False

for X in range(30,51):
    for Y in range(30,51):
        
        classifier = MLPClassifier(max_iter=1000,alpha = 0.1,random_state=0, hidden_layer_sizes=[X,Y])
        classifier.fit(x_train, y_train)
        tmp_train = classifier.score(x_train, y_train) * 100
        tmp_test = classifier.score(x_test, y_test) * 100
        
        if(tmp_train > result_train and tmp_test > result_test):
            if(abs(tmp_test - tmp_train) >= 0 and abs(tmp_test - tmp_train) <= 3):
                print("X와 Y", X, Y)
                print("훈련과 테스트 점수", tmp_train , tmp_test)
                print("=========================================")
                flag = True
                result_train = tmp_train
                result_test = tmp_test
                result_X = X
                result_Y = Y


print("Search End")

if(flag == True):
     classifier = MLPClassifier(max_iter=1000,alpha = 0.1,random_state=0, hidden_layer_sizes=[result_X,result_Y]).fit(x_train, y_train)
else:
    classifier = svm.SVC(gamma=1, C=1.0).fit(x_train, y_train)


스케일 조정 전 특성별 최소값: 
 [ 0.     0.     0.     0.     0.     0.     0.078 21.   ]
스케일 조정 전 특성별 최대값: 
 [ 17.   198.   122.    99.   846.    67.1    2.42  81.  ]
변환 된 후 크기 (576, 8)
스케일 조정 후 특성별 최소값: 
 [0. 0. 0. 0. 0. 0. 0. 0.]
스케일 조정 후 특성별 최대값: 
 [1. 1. 1. 1. 1. 1. 1. 1.]
X와 Y 30 45
훈련과 테스트 점수 81.94444444444444 80.20833333333334


E:\Python\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


X와 Y 32 35
훈련과 테스트 점수 82.29166666666666 80.72916666666666
X와 Y 33 47
훈련과 테스트 점수 83.68055555555556 81.77083333333334


E:\Python\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Search End


In [4]:
print("훈련 세트 정확도: {:.2f}%".format(classifier.score(x_train, y_train) * 100))
print("테스트 세트 정확도: {:.2f}%".format(classifier.score(x_test, y_test) * 100))

훈련 세트 정확도: 83.68%
테스트 세트 정확도: 81.77%
