In [15]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [47]:
input_file = './data/pima-indians-diabetes.data.csv'
data = np.loadtxt(input_file, delimiter=',')
x, y = data[:, :-1], data[:, -1]
print(data.shape)
print(x[0:5])
print(y[0:5])
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(768, 9)
[[6.000e+00 1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01
  5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]]
[1. 0. 1. 0. 1.]
(576, 8)
(576,)
(192, 8)
(192,)


In [48]:
from sklearn import svm
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


newData = [[1,103,30,38,83,43.3,0.183,3]]
newData = scaler.transform(newData)
print(x_test)

classifier = svm.SVC(gamma=1, C=1.0).fit(x_train, y_train)
print(classifier.predict(x_test))
print(classifier.predict(newData))

print("훈련 세트 정확도: {:.2f}%".format(classifier.score(x_train, y_train) * 100))
print("테스트 세트 정확도: {:.2f}%".format(classifier.score(x_test, y_test) * 100))

[[0.05882353 1.00505051 0.62295082 ... 0.63934426 0.56191289 0.01666667]
 [0.11764706 0.54040404 0.60655738 ... 0.50074516 0.13919727 0.03333333]
 [0.23529412 0.38383838 0.50819672 ... 0.50670641 0.13364646 0.06666667]
 ...
 [0.05882353 0.55050505 0.49180328 ... 0.37853949 0.37105038 0.        ]
 [0.17647059 0.64646465 0.63934426 ... 0.31445604 0.08112724 0.56666667]
 [0.29411765 0.44444444 0.63934426 ... 0.41132638 0.07685739 0.26666667]]
[1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.
 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.
 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.