In [2]:
import cv2
import numpy as np

In [3]:
img = cv2.imread("./data/Lenna.png")

print("img.ndim=", img.ndim) 
print("img.shape=", img.shape)
print("img.dtype=", img.dtype)

# """
# ndim 은 차원
# shape은 크기
# dyep은 데이터 타입
# """

img.ndim= 3
img.shape= (512, 512, 3)
img.dtype= uint8


In [4]:
img = img.astype(np.int32)
print("img.dtype : ", img.dtype)

# """
# 데이터 타입을 변형시키는 것
# 변형 시킬 때 astype으로 변형이 가능하고 np.uint8 이렇게도 가능하다.
# """

img.dtype :  int32


In [5]:
img = np.uint8(img)
print("img.dtype : ", img.dtype)

img.dtype :  uint8


In [6]:
img = cv2.imread("./data/Lenna.png", cv2.IMREAD_GRAYSCALE)
print("img.shape : ", img.shape)

# """
# cv2.IMREAD_GRAYSCALE은 그레이 영상으로 읽어라는 것과 동일하다.
# """

img.shape :  (512, 512)


In [7]:
img = img.reshape(img.shape[0]*img.shape[1]) #img = img.flatten()
print("img.shape = ", img.shape)

# """
# reshape은 영상의 크기의 모양을 변형시키니다.
# 이것은 2창원(512,512) 영상을 1차원 영상으로 변형시킨 것이다.
# 즉 이말은 100 * 100 영상을
# 1 * 10000 으로 변형시킨 것이다.

# """

img.shape =  (262144,)


In [8]:
img = img.reshape(512,512)
print("img.shape : ", img.shape)

img.shape :  (512, 512)


In [9]:
cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
img = cv2.imread("./data/Lenna.png", cv2.IMREAD_GRAYSCALE)
img[100,200] = 0
# """
#  이것은 y = 100 이고 x = 200의 밝기값을 0으로 한다.
#  만약에 칼라라면 (0,0,0) 이렇게 하여 밝기 값을 0으로 한다.
# """
print(img[100:110, 200:210]) #R이 접근
# """
# 이 부분이 슬라이싱
# 이 영역의 값을 출력 해봐라
# y 축은 100 에서 109 까지 출력하고
# x 축은 200에서 209까지 출력해보라

# 밝기값이 저장되어 있다.
# """

img[100:400, 200:300] = 0

# """
# 와이 축은 100에서 399까지 0으로
# 엑스 축은 200에서 299까지 0으로 채워라
# """

cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

[[  0 153 150 141 151 150 151 145 144 144]
 [146 144 151 155 148 149 146 148 145 145]
 [139 146 157 148 142 146 148 146 144 140]
 [145 153 146 135 139 147 149 148 140 138]
 [151 149 139 142 148 150 149 141 142 147]
 [151 144 143 151 152 150 139 138 145 144]
 [149 151 149 151 149 148 150 143 142 141]
 [159 149 145 146 150 151 152 144 132 137]
 [151 144 144 144 152 149 139 134 140 144]
 [142 142 151 151 143 142 133 143 146 136]]


In [11]:
img = cv2.imread("./data/Lenna.png")
img[100,200] = [255,0,0] #파랑색으로 해준다.
print(img[100,200:210])

img[100:400, 200:300] = [255,0,0] #(0,0,255)는 빨강색 (0,255,0)은 초록색 (255,0,0)은 파랑색 => BRG

cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

[[255   0   0]
 [109 117 213]
 [113 115 208]
 [114 101 199]
 [121 116 207]
 [105 114 209]
 [112 113 212]
 [107 109 204]
 [117 108 200]
 [110 109 202]]


In [12]:
img[100:400, 200:300, 0] = 255 #R-채널을 255로 변경
img[100:400, 300:400, 1] = 255 #G-채널을 255로 변경
img[100:400, 400:500, 2] = 255 #R-채널을 25로 변경

# """
# 이 것은 칼라 영상이기 때문에 3차원이다.
# 0은 파랑색
# 1은 초록색
# 2는 빨강색 
# 채널을 의미하낟.

# 그리고 숫자가 낮으면 낮을 수록 색의 농도가 찐해진다.
# """

cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()