In [1]:
import cv2
import numpy as np

In [3]:
img =cv2.imread("./data/Lenna.png", cv2.IMREAD_GRAYSCALE)

(h,w) = img.shape #이미지의 크기를 가져온다.
print(h,w)

cy, cx = h//2, w//2 #이미지의 절반을 가져온다.
print(cy,cx)

roi = img[0:cy, 0:cx]

cv2.imshow("ROI", roi)
cv2.waitKey()
cv2.destroyAllWindows()

512 512
256 256


In [2]:
src = cv2.imread("./data/Lenna.png",cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype=src.dtype)

# """
# dst라는 영상을 만드는데, src.shape 만큼 크기의 영상을 만들어라 그리고
# 데이터 타입을 넣어주는데, 전체가 0이라서 검정색이 된다.
# """

N = 4 
# 평균영상을 구하는 것이다. 즉화면을 높이를 4줄로 가로를 4줄로 나눈다를 의미한다.
height, width = src.shape
h = height //N
w = width // N

for i in range(N):
    for j in range(N):
        y = i*h
        x = j*w
        roi = src[y:y+h, x:x+w]
        val = cv2.mean(roi) #roi의 평균값을 넣어준다.
        print(val)
        dst[y:y+h, x:x+w] = val[0]
#         """
#         이렇게 한다면 검정화면인 dst에 val값을 넣어준다.
#         이 때 val이 [0]인 이유는 mean이 4차원이기 때문에
#         그중에 0번 채널을 넣어주는 것이다.
#         """
        
cv2.imshow("dst", dst)
cv2.waitKey()
cv2.destroyAllWindows()

(134.8477783203125, 0.0, 0.0, 0.0)
(146.747802734375, 0.0, 0.0, 0.0)
(152.968994140625, 0.0, 0.0, 0.0)
(123.6239013671875, 0.0, 0.0, 0.0)
(130.52777099609375, 0.0, 0.0, 0.0)
(126.67645263671875, 0.0, 0.0, 0.0)
(164.22821044921875, 0.0, 0.0, 0.0)
(134.36572265625, 0.0, 0.0, 0.0)
(118.12847900390625, 0.0, 0.0, 0.0)
(103.7271728515625, 0.0, 0.0, 0.0)
(126.73822021484375, 0.0, 0.0, 0.0)
(164.34765625, 0.0, 0.0, 0.0)
(106.5555419921875, 0.0, 0.0, 0.0)
(97.04498291015625, 0.0, 0.0, 0.0)
(159.75433349609375, 0.0, 0.0, 0.0)
(128.5537109375, 0.0, 0.0, 0.0)


In [6]:
src = cv2.imread("./data/Lenna.png",cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src) #마우스로 영역을 선택하는 것 -> 마우스로 선택하면 저장이 roi에 저장된다.
print("roi =", roi)

#X, Y, width , height 값이 roi에 저장이 된다.

image = src[roi[1]:roi[1] + roi[3], roi[0]:roi[0] + roi[2]]

cv2.imshow("image", image)
cv2.waitKey()
cv2.destroyAllWindows()

roi = (71, 72, 318, 244)


In [4]:
rects = cv2.selectROIs("src", src, False, False) 
print("rects =", rects)

for r in rects:
    cv2.rectangle(src, (r[0], r[1]), (r[0]+r[2], r[1]+r[3]), 255)

cv2.imshow("src", src)
cv2.waitKey()
cv2.destroyAllWindows()

# """
# 이것은 roi를 여러개 선택할 수 있도록 한 것이다. 

# 사용 방법은 선택을 하고 스페이스바를 누르고 난뒤 ESC를 누르면 아래 처럼 나온다.
# """

rects = [[276 138 217 198]
 [109 127 184 167]
 [189 195 239 160]
 [172 201 118 225]
 [251 119 149 141]
 [ 90 136 266 189]
 [ 90 136 266 189]
 [ 90 136 266 189]
 [ 90 136 266 189]
 [196 179 135 156]
 [196 179 135 156]
 [196 179 135 156]
 [196 179 135 156]
 [196 179 135 156]
 [196 179 135 156]
 [196 179 135 156]
 [196 179 135 156]]


'\n이것은 roi를 여러개 선택할 수 있도록 한 것이다. \n'