In [6]:
import cv2
import numpy as np

In [7]:
def onChange(pos): #pos라는 변수를 통해서 넘어온다.
    global image 
    r = cv2.getTrackbarPos("Bright", "img")
    temp = np.uint8((r/100) * image) #img값을 바꿔준다.
    print(temp)
    cv2.imshow("img", temp)


src = cv2.imread("./data/Baboon.png", 0)
roi = cv2.selectROI(src)
image = src[roi[1]:roi[1] + roi[3], roi[0]:roi[0] + roi[2]]
cv2.imshow("img", image )

#트랙바 생성
cv2.createTrackbar("Bright", "img", 0, 100, onChange)

cv2.setTrackbarPos("Bright","img",100)

cv2.waitKey()
cv2.destroyAllWindows()

[[ 57  60 113 ...  72 111 156]
 [115 132 170 ...  80  87 157]
 [124 138 159 ...  93  91 102]
 ...
 [114 130 150 ... 142 143 140]
 [129 141 143 ... 174 161 158]
 [156 141 126 ... 123 158 187]]
[[ 56  59 111 ...  71 109 154]
 [113 130 168 ...  79  86 155]
 [122 136 157 ...  92  90 100]
 ...
 [112 128 148 ... 140 141 138]
 [127 139 141 ... 172 159 156]
 [154 139 124 ... 121 156 185]]
[[ 55  58 110 ...  70 108 152]
 [112 129 166 ...  78  85 153]
 [121 135 155 ...  91  89  99]
 ...
 [111 127 147 ... 139 140 137]
 [126 138 140 ... 170 157 154]
 [152 138 123 ... 120 154 183]]
[[ 55  58 109 ...  69 107 151]
 [111 128 164 ...  77  84 152]
 [120 133 154 ...  90  88  98]
 ...
 [110 126 145 ... 137 138 135]
 [125 136 138 ... 168 156 153]
 [151 136 122 ... 119 153 181]]
[[ 54  57 107 ...  68 105 148]
 [109 125 161 ...  76  82 149]
 [117 131 151 ...  88  86  96]
 ...
 [108 123 142 ... 134 135 133]
 [122 133 135 ... 165 152 150]
 [148 133 119 ... 116 150 177]]
[[ 53  55 105 ...  66 103 145]
 [106 122

[[24 25 48 ... 30 47 67]
 [49 56 73 ... 34 37 67]
 [53 59 68 ... 39 39 43]
 ...
 [49 55 64 ... 61 61 60]
 [55 60 61 ... 74 69 67]
 [67 60 54 ... 52 67 80]]
[[23 24 46 ... 29 45 63]
 [47 54 69 ... 32 35 64]
 [50 56 65 ... 38 37 41]
 ...
 [46 53 61 ... 58 58 57]
 [52 57 58 ... 71 66 64]
 [63 57 51 ... 50 64 76]]
[[22 24 45 ... 28 44 62]
 [46 52 68 ... 32 34 62]
 [49 55 63 ... 37 36 40]
 ...
 [45 52 60 ... 56 57 56]
 [51 56 57 ... 69 64 63]
 [62 56 50 ... 49 63 74]]
[[22 23 44 ... 28 43 60]
 [44 51 66 ... 31 33 61]
 [48 53 62 ... 36 35 39]
 ...
 [44 50 58 ... 55 55 54]
 [50 54 55 ... 67 62 61]
 [60 54 49 ... 47 61 72]]
[[20 21 40 ... 25 39 56]
 [41 47 61 ... 28 31 56]
 [44 49 57 ... 33 32 36]
 ...
 [41 46 54 ... 51 51 50]
 [46 50 51 ... 62 57 56]
 [56 50 45 ... 44 56 67]]
[[19 20 38 ... 24 37 53]
 [39 44 57 ... 27 29 53]
 [42 46 54 ... 31 30 34]
 ...
 [38 44 51 ... 48 48 47]
 [43 47 48 ... 59 54 53]
 [53 47 42 ... 41 53 63]]
[[17 18 35 ... 22 34 48]
 [35 40 52 ... 24 26 48]
 [38 42 49 ...